# Generated by Django 3.2 on 2023-06-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
