# Generated by Django 3.2 on 2023-07-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
